[package]
name = "sri"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
base64 = { workspace = true }
sha-1 = { workspace = true }
sha2 = { workspace = true }
